name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
  
    - name: locked_user.js
      run: make locked_user.js
      
    - name: systemwide_user.js
      run: make systemwide_user.js
      
    - name: policies.json
      run: make policies.json
      
    - name: cat locked_user.js
      run: cat locked_user.js
      
    - name: cat systemwide_user.js
      run: cat systemwide_user.js
      
    - name: cat policies.json
      run: cat policies.json
