name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ locked_user.js ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
  
    - name: Install dependencies
      run: make
      
    - name: Run check
      run: make check
      
    - name: Run distcheck
      run: make distcheck
      
    - name: locked_user.js
      run: make locked_user.js
      
    - name: systemwide_user.jss
      run: make systemwide_user.js
      
    - name: policies.json
      run: make policies.json
